/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// ⚠️ SECURITY: Never fallback to hardcoded values - always use environment variables
// If these throw an error, it means your .env.local file is missing VITE_SUPABASE_PROJECT_ID
const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!projectId) {
  throw new Error(
    'Missing VITE_SUPABASE_PROJECT_ID in environment variables. ' +
    'Add it to your .env.local file from your Supabase project dashboard.'
  );
}

if (!publicAnonKey) {
  throw new Error(
    'Missing VITE_SUPABASE_ANON_KEY in environment variables. ' +
    'Add it to your .env.local file from your Supabase project dashboard.'
  );
}

export { projectId, publicAnonKey };