/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_28f2f653 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/mcbbtrrhqweypfnlzwht/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    console.error('[KV Store] Missing environment variables!');
    console.error('[KV Store] SUPABASE_URL:', url ? 'exists' : 'MISSING');
    console.error('[KV Store] SUPABASE_SERVICE_ROLE_KEY:', key ? 'exists' : 'MISSING');
    throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  }
  
  // CRITICAL: Configure client to bypass RLS with service role
  return createClient(url, key, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
      detectSessionInUrl: false
    },
    db: {
      schema: 'public'
    }
  });
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_28f2f653").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_28f2f653").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return { value: data?.value }; // Return as object with value property
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_28f2f653").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_28f2f653").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_28f2f653").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_28f2f653").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  console.log(`[KV Store] getByPrefix called with prefix: "${prefix}"`);
  
  const { data, error } = await supabase.from("kv_store_28f2f653").select("key, value").like("key", prefix + "%");
  
  if (error) {
    console.error(`[KV Store] ERROR in getByPrefix:`, error);
    console.error(`[KV Store] Error code:`, error.code);
    console.error(`[KV Store] Error message:`, error.message);
    console.error(`[KV Store] Error details:`, error.details);
    throw new Error(error.message);
  }
  
  console.log(`[KV Store] getByPrefix found ${data?.length || 0} items`);
  return data ?? []; // Return both key and value
};