-- Migration: Create activity_logs table
-- Purpose: Track user actions, sessions, and engagement metrics
-- Created: 2026-04-02

-- Create activity_logs table
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    user_name TEXT NOT NULL,
    user_role TEXT NOT NULL DEFAULT 'unknown',
    action TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    session_id TEXT,
    device_info JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Indexes for performance
    CONSTRAINT activity_logs_user_id_check CHECK (length(user_id) <= 255),
    CONSTRAINT activity_logs_user_name_check CHECK (length(user_name) <= 255),
    CONSTRAINT activity_logs_action_check CHECK (length(action) <= 100)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action ON public.activity_logs(action);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_session_id ON public.activity_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_role ON public.activity_logs(user_role);

-- Create a partial index for recent activities (last 30 days)
CREATE INDEX IF NOT EXISTS idx_activity_logs_recent ON public.activity_logs(created_at DESC) 
WHERE created_at >= NOW() - INTERVAL '30 days';

-- Add RLS (Row Level Security) policies
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only view their own activity logs
CREATE POLICY "Users can view own activity logs" ON public.activity_logs
    FOR SELECT USING (auth.uid()::text = user_id);

-- Policy: Users can insert their own activity logs
CREATE POLICY "Users can insert own activity logs" ON public.activity_logs
    FOR INSERT WITH CHECK (auth.uid()::text = user_id);

-- Policy: Service role can do anything (for backend functions)
CREATE POLICY "Service role full access" ON public.activity_logs
    FOR ALL USING (auth.role() = 'service_role');

-- Grant permissions
GRANT SELECT ON public.activity_logs TO authenticated;
GRANT INSERT ON public.activity_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activity_logs TO service_role;

-- Add helpful comments
COMMENT ON TABLE public.activity_logs IS 'Tracks user actions, sessions, and engagement metrics for the Airtel Champions PWA';
COMMENT ON COLUMN public.activity_logs.user_id IS 'Identifier of the user who performed the action';
COMMENT ON COLUMN public.activity_logs.user_name IS 'Display name of the user';
COMMENT ON COLUMN public.activity_logs.user_role IS 'Role of the user (sales, hbb, admin, etc.)';
COMMENT ON COLUMN public.activity_logs.action IS 'Type of action performed (login, page_view, etc.)';
COMMENT ON COLUMN public.activity_logs.metadata IS 'Additional context and details about the action';
COMMENT ON COLUMN public.activity_logs.session_id IS 'Unique identifier for the user session';
COMMENT ON COLUMN public.activity_logs.device_info IS 'Information about the device and browser used';
